const sentences = [
  "I have found it! 🎉",
  "Eureka! I've found it! 🕺",
  "Hurray! I've found it! 🥳",
  "I've located it! 🌟",
  "Yahoo! I've found it! 🎈",
  "Amazing! I've found it! ✨",
  "Voila! I've found it! 🎁",
  "Ahoy! I've found it! ⚓️",
  "Success! I've found it! 🎯",
  "Bravo! I've found it! 👏",
  "Look! I've found it! 👀",
  "Great news! I've found it! 🎊",
  "Ta-da! I've found it! 🎵",
  "Fantastic! I've found it! 🌈",
  "Bingo! I've found it! 🎲",
  "Yippee! I've found it! 🤩",
  "Hurrah! I've found it! 🎇",
  "Hip hip hooray! I've found it! 🙌",
  "Check it out! I've found it! 🔍",
  "Incredible! I've found it! 🚀",
  "🎉 Hurray! I've found it! 🙌",
  "✨ Eureka! I've located it! 🕺",
  "🥳 Yahoo! I've uncovered it! 💃",
  "🎈 Balloon celebration! I've retrieved it! 🎁",
  "🎵 Music to my ears! I've obtained it! 🎶",
  "🌟 Bright revelation! I've revealed it! 🎯",
  "🚀 Mission accomplished! I've achieved it! 🎇",
  "🎆 Spectacular find! I've recovered it! 🎺",
  "🎻 Melodic triumph! I've captured it! 🪅",
  "🎉 Guess what? I've found it! 🙌",
  "✨ Incredible news! I've located it! 🕺",
  "🥳 Celebration time! I've uncovered it! 💃",
  "🎈 Big announcement! I've retrieved it! 🎁",
  "🎵 Amazing discovery! I've obtained it! 🎶",
  "🌟 Unbelievable moment! I've revealed it! 🎯",
  "🚀 Monumental achievement! I've achieved it! 🎇",
  "🎆 Remarkable breakthrough! I've recovered it! 🎺",
  "🎻 Harmonious triumph! I've captured it! 🪅",
  "🎉 Exciting revelation! I've found it! 🙌",
  "✨ Thrilling news! I've located it! 🕺",
  "🥳 Wonderful discovery! I've uncovered it! 💃",
]

const getRandomSentenceWithEmoji = () => {
  const randomIndex = Math.floor(Math.random() * sentences.length)
  return sentences[randomIndex]
}
export default getRandomSentenceWithEmoji
